# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Soybean Tracker' do

  use_frameworks!

  # Pods for Soybean Tracker.
 pod 'Alamofire', '~> 4.0'
 pod 'AlamofireImage', '~> 3.1'

end
